### ISSUE TITLE
User after-confirmation email is not sent

### ISSUE THREAD

**Issue by geekdevs** [dachcom-digital/pimcore-members#33]
Even when setting `send_user_mail_after_confirmed: true`after-confirmation email does not send.

This is likely the issue:
https://github.com/dachcom-digital/pimcore-members/blob/7f33d34ae9fb7fd77ed133e61b595a1c62c6b470/src/MembersBundle/EventListener/UserChangeListener.php#L55

`$this->configuration->getConfig('post_register_type') !== 'confirm_by_admin'`

` !==`  should be ` ===` here I believe so that it won't send email if confirmed by admin and would send it otherwise.

**Comment by solverat** [comment]
Hey @geekdevs. This is the right behaviour. Let me explain: 

Members only sends a confirmation mail to user if `post_register_type` is set to `confirm_by_admin`. Because only than it's necessary to inform the user about his confirmation state, otherwise he will see the confirmation after he clicked on the confirmation link. 

If you want to submit a mail to user in any state, you need to implement an event by yourself. Use the Events to do so:


## Configuration

```yml
services:
    AppBundle\EventListener\PostRegistrationListener:
        tags:
            - { name: kernel.event_subscriber }
```

## PHP Class
```php
<?php

namespace AppBundle\EventListener;

use MembersBundle\Adapter\User\UserInterface;
use MembersBundle\Event\FilterUserResponseEvent;
use MembersBundle\Event\FormEvent;
use MembersBundle\Mailer\Mailer;
use MembersBundle\MembersEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class PostRegistrationListener implements EventSubscriberInterface
{
    /**
     * @var Mailer
     */
    protected $mailer;

    /**
     * PostRegistrationListener constructor.
     *
     * @param Mailer $pimcoreMailer
     */
    public function __construct(Mailer $pimcoreMailer)
    {
        $this->mailer = $pimcoreMailer;
    }

    /**
     * @return array
     */
    public static function getSubscribedEvents()
    {
        return [
            MembersEvents::REGISTRATION_CONFIRMED => 'onRegistrationConfirmed',
        ];
    }

    /**
     * @param FilterUserResponseEvent $event
     */
    public function onRegistrationConfirmed(FilterUserResponseEvent $event)
    {
        /** @var $user UserInterface */
        $user = $event->getUser();
        $this->mailer->sendConfirmedEmailMessage($user);
    }
}
``` 

Hope this helps.
