### ISSUE TITLE
[Frontend Routes] Members routes overwrite pimcore static routes

### ISSUE THREAD

**Issue by aarongerig** [dachcom-digital/pimcore-members#35]
Whenever I'd like to create my own pimcore static routes to overwrite the default MemberBundle routes, my routes are overridden by the default one's.

For example:
```php
// Should overwrite the login route
1 => [
    "id" => 1,
    "name" => "members_user_security_login",
    "pattern" => "/^\\/[a-z]{2}\\/login/",
    "reverse" => "/%_locale/login",
    "module" => "MembersBundle",
    "controller" => "Auth",
    "action" => "login",
    "variables" => "_locale",
    ...
],
```

```php
// Redirect to login page
public function defaultAction()
{
    return $this->redirect($this->get('router')->generate('members_user_security_login'));
}
```

This should redirect me to `http://domain.com/de/login` instead it redirects me to `http://domain.com/de/members/login`.

Am I missing something? If not, could the routing be refactored so the routes may be overridden?

Thanks! 😄

**Comment by solverat** [comment]
hey @aarongerig. The Problem is: staticroutes have a [lower priority](https://pimcore.com/docs/5.0.x/Development_Documentation/MVC/Routing_and_URLs/index.html#page_4-Static-Routes-Custom-Routes) than symfony routes.
But we just had the same problem - even if you want to override the members routes in your app config, the priority is still a problem (it only works if you have a additional bundle with a higher priority than members.)

I just created an issue (#36) for that.

**Comment by aarongerig** [comment]
Thanks @solverat ! Yeah, I've tried it with the app configs as well. Would be great to have this kind of power over the default Members routes. If I can contribute in any way, let me know.

Going to close this for now.

**Comment by solverat** [comment]
Hey @aarongerig, i just changed the routing inclusion. 
Route installation: https://github.com/dachcom-digital/pimcore-members#route-installation

Maybe you could test it? Thanks!

We're also working on a CoreShop implementation, so for now i'll will wait for the 2.1 release!

**Comment by aarongerig** [comment]
Awesome! Will test that asap (probably tomorrow) and will let you know about any inconveniences.
