### ISSUE TITLE
Profile edit does not check for existing username when it is changed

### ISSUE THREAD

**Issue by LosHawlos** [dachcom-digital/pimcore-members#40]
The edit profile form allows to change the username. But it does noch check for the new username to be alredy in use. So I'm able to change it to an already existing username. After that none of the 2 users is able to login.

Steps to reproduce:
1) Register new user "aaa" and activate the account
2) Register new user "bbb" and activate the account.
3) Login as user "bbb" and use the profile edit form an change the username to "aaa"
=> This does not trigger an error, the new username is written to the user object.
4) Try to login using username "aaa" (which is now the username of 2 users)
=> None of the 2 passwords work. Login no longer possible

**Comment by LosHawlos** [comment]
The same happens when registering as new user. I can register using a username that is already in use, and activate the account. Later on I can not log in using this username.

**Comment by solverat** [comment]
Hey @LosHawlos, thank for the report. Actually the uniqueness validator was never implemented for such cases. Until now! :) You may want to check out the latest dev-master commit.
**Important**: In case you have duplicate user data in your db, you need to get rid of them first otherwise the validator will not work.

Todo: check for uniqueness in backend!

**Comment by dpfaffenbauer** [comment]
regarding uniqueness: you can set text-fields to be unique in pimcore objects. it then actually uses a database constraint.

**Comment by solverat** [comment]
done. so this should work now. if not - just reopen this issues. thanks!
