### ISSUE TITLE
Session problem

### ISSUE THREAD

**Issue by Maksonis** [dachcom-digital/pimcore-members#8]
When I tried to use this plugin with Hybridauth in pimcore I get this error: 
`PHP Fatal error:  Uncaught Zend_Session_Exception: session has already been started by session.auto-start or session_start()`
How I can fix this ?
Thanks.

**Comment by solverat** [comment]
HybridAuth is currently not supported in Members. However, because of the upcoming pimcore5 release and its new way to [implement frontend authentication](https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/19_Development_Tools_and_Details/10_Security_Authentication/01_Authenticate_Pimcore_Objects.md) we'll focus on Members 2.0 which will probably support additional auth wrapper like Hybridauth.
