### ISSUE TITLE
too few arguments for RoleOptionsProvider

### ISSUE THREAD

**Issue by dasraab** [dachcom-digital/pimcore-members#98]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Pimcore Version: 5.8.4
Members Version: 2.4

I do get the following error when i try to open existing Fieldcollections on the frontend.
Seems like the autowiring is not working for some reason.

```
Message: Type error: Too few arguments to function MembersBundle\CoreExtension\Provider\RoleOptionsProvider::__construct(), 0 passed in /home/forge/teens.fit-4-future.de/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php on line 45 and exactly 1 expected
```

Any idea how to fix that?

**Comment by solverat** [comment]
Hey, @dasraab. In the latest release, this class has been to changed to a symfony service. Have executed the migration update?

- `pimcore:migrations:migrate -b MembersBundle`
- Or via extension manager in backend (green `+` symbol)

**Comment by dasraab** [comment]
Hi @solverat and thanks for your answer. if i try your command it says no "no migrations to execute". i also tried reinstalling the package and clearing my caches but that also didn't help. maybe fieldcollections aren't automatically autowired and therefore constructor injection is not working for them?

**Comment by dasraab** [comment]
bin/console debug:autowiring RoleOptionsProvider shows '  MembersBundle\CoreExtension\Provider\RoleOptionsProvider' so autowiring seems to work fine

**Comment by solverat** [comment]
Just to be sure, it's configured like this, right?

![image](https://user-images.githubusercontent.com/700119/58700612-d4d14000-83a0-11e9-8e80-20fee0500bcd.png)

**Comment by dasraab** [comment]
ok now i feel pretty stupid... i forgot the @ at the beginning... can you maybe explain in short why the @ is so important here? i'm pretty new to symfony and want to learn as much as i can.

thanks stefan!

**Comment by solverat** [comment]
Don't worry! The @ sign means, that the symfoy service (loaded from the container) with all its dependencies should be requested. Without this sign, the default class will be instantiated as plain one (`new Class()`). 

But in fact, this shouldn't bother you in the first place, because there is [Migration](https://github.com/dachcom-digital/pimcore-members/blob/master/src/MembersBundle/Migrations/Version20190508092938.php) which takes care about it. In the previous MembersBundle version, this OptionProvider was just a simple class indeed and has been changed to a symfony service. So I'm wondering why it's not in your case. 

It also should be available on a fresh class install:

https://github.com/dachcom-digital/pimcore-members/blob/b4139f6864ceccc72a6f00dc3618653bc6d2274a/src/MembersBundle/Resources/install/classes/class_MembersGroup_export.json#L69

So my question here is: Why did this happen to you? Have you created your classes manually?

**Comment by dasraab** [comment]
Hi Stefan, thank you so much for your answer. now everything makes sense. the reason why it didn't update the classes was indeed cause i created them on my own (without the installer console command) - i also didn't delete the classes when i reinstalled the bundle cause i couldn't think of a reason why this should be a problem - now i know better :P 

Thanks again!
